In [23]:
import numpy as np
import scipy as sp
from sklearn.naive_bayes import MultinomialNB
from sklearn.neural_network import MLPClassifier as mlp
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import pandas as pd
from sklearn.cross_validation import train_test_split as tts

In [5]:
df = pd.read_csv("C:/Users/Visha/Desktop/Datasets/data.csv", sep = '\t', names = ['label', 'message'], index_col =None)

In [6]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df.loc[df['label'] == 'ham', 'label'] = 1
df.loc[df['label'] == 'spam', 'label'] = 0

In [8]:
df.head()

label                                            message
0     1  Go until jurong point, crazy.. Available only ...
1     1                      Ok lar... Joking wif u oni...
2     0  Free entry in 2 a wkly comp to win FA Cup fina...
3     1  U dun say so early hor... U c already then say...
4     1  Nah I don't think he goes to usf, he lives aro...

In [9]:
X_train, X_test, y_train, y_test = tts(df['message'], df['label'], test_size = 0.33, random_state = 7)

In [10]:
X_test.shape

(1839,)

In [11]:
y_test.shape

(1839,)

In [12]:
X_train.shape

(3733,)

In [13]:
cv = TfidfVectorizer(stop_words = 'english', min_df = 1)

In [14]:
cv1 = CountVectorizer()

In [15]:
X_traincv = cv1.fit_transform(X_train)
X_testcv = cv1.transform(X_test)

In [16]:
X_test.iloc[0]

'You will be in the place of that man'

In [24]:
a = cv.fit_transform(["How r u doing?", "Wassup nigga?", "Just go to hell"])

In [25]:
a.toarray()

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.70710678,  0.70710678],
       [ 0.        ,  0.70710678,  0.70710678,  0.        ,  0.        ]])

In [28]:
type(a)

scipy.sparse.csr.csr_matrix

In [27]:
cv.get_feature_names()

['doing', 'hell', 'just', 'nigga', 'wassup']

In [29]:
X_traincv.toarray()

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [17]:
y_train = y_train.astype('int64')
y_test = y_test.astype('int64')

In [30]:
clf = mlp(activation = 'relu', solver = 'sgd', random_state = 1, max_iter = 1000)

In [31]:
clf.fit(X_traincv, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='sgd', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [32]:
clf.score(X_testcv, y_test)

0.98151169113648717

In [132]:
a = cv1.transform(["Hello!!! My name is Mayya. I to look a structure at a site. You to interest me as the man. To me to want it is more to know about you. Now it is very difficult to find the person whom to begin the present friend. Not speaking about the man to go a life together. And consequently I have decided to write to you the letter. It is a little to write about itself.To me of 28 years, single. As To love sports, I do not smoke. My friends speak about me that I very interesting person and they very much like to communicate with me. To not know what to write about itself. If to you to become interesting, you to write to me the letter."])

In [133]:
clf.predict(a)

array([1], dtype=int64)